
# use_retrieve: false

inference:
  # model_name: llama3.1-405b-instruct 
  model_name: deepseek-r1
  data_dir: ./data
  dataset: FinanceReasoning
  subset:  hard 
  output_dir: ./results
  prompt:
    prompt_type: cot 

evaluation:
  result_dir: ./results
  ans_extract_model_name: gpt-4o-mini-2024-07-18
  model_name: deepseek-r1
  dataset: FinanceReasoning
  subset: hard 
  prompt_type: cot 
  force_extract_answer: false 
  timeout_duration: 10

llms:
  # https://api-docs.deepseek.com/
  deepseek-r1:
    model_id: deepseek-reasoner
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: true
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
      top_p: 1.0

  deepseek-v3:
    model_id: deepseek-chat
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: false 
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
      top_p: 1.0

  # https://platform.openai.com/docs/models
  gpt-4o-mini-2024-07-18:
    model_id: gpt-4o-mini-2024-07-18
    api_key: <your_api_key>
    support_system_role: true
    reasoner: false
    max_retries: 5
    sampling_args:
      temperature: 0.0
    rpm: 500

  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    api_key: <your_api_key>
    support_system_role: true
    reasoner: false
    sampling_args:
      temperature: 0.0
      top_p: 1.0
    rpm: 60

  o1-2024-12-17:
    model_id: o1-2024-12-17
    api_key: <your_api_key>
    support_system_role: true
    reasoner: true
    rpm: 10

  o3-mini-2025-01-31:
    model_id: o3-mini-2025-01-31
    api_key: <your_api_key>
    support_system_role: true
    reasoner: true
    rpm: 300

  o1-mini-2024-09-12:
    model_id: o3-mini-2025-01-31
    api_key: <your_api_key>
    support_system_role: false 
    reasoner: true
    rpm: 300

  # https://docs.anthropic.com/en/api/
  claude-3-5-sonnet-20241022:
    model_id: claude-3-5-sonnet-20241022
    api_key: <your_api_key>
    api_style: claude
    reasoner: false
    support_system_role: false 
    sampling_args:
      max_tokens: 8192
    rpm: 30
  
  # https://www.alibabacloud.com/help/model-studio/
  qwen-max-2025-01-25:
    model_id: qwen-max-2025-01-25
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: false 
    max_retries: 5
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
    rpm: 60
  
  qwq-32b-preview:
    model_id: qwq-32b-preview
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: true 
    sampling_args:
      temperature: 0.0
    rpm: 300

  llama3.1-405b-instruct:
    model_id: llama3.1-405b-instruct
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: false 
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
    rpm: 10 

  llama3.3-70b-instruct:
    model_id: llama3.3-70b-instruct
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true
    reasoner: false 
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
    rpm: 10 

  # https://ai.google.dev/gemini-api/docs/openai
  gemini-1.5-flash:
    model_id: gemini-1.5-flash
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true 
    reasoner: false 
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
      top_p: 1.0
    rpm: 10

  gemini-2.0-flash-thinking-exp-01-21:
    model_id: gemini-2.0-flash-thinking-exp-01-21
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true 
    reasoner: true 
    sampling_args:
      temperature: 1
      top_p: 1.0
      max_tokens: 8192
    rpm: 3
  
  gemini-2.0-pro-exp-02-05:
    model_id: gemini-2.0-pro-exp-02-05
    api_key: <your_api_key>
    base_url: <your_base_url>
    support_system_role: true 
    reasoner: false 
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
      top_p: 1.0
    rpm: 3

